### ISSUE TITLE
開発者として、正しくない URL へアクセスされたときにはそれをユーザに知らせたい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kajaeru#100]
開発者として、正しくない URL へアクセスされたときにはそれをユーザに知らせたい。
なぜなら、ユーザに「何が起きたのか」を伝えれば、次はどうやって使用したらいいかをわかってもらえるからだ。

**Comment by shokola** [comment]
うーん、RESTful#とは主催者としてこれはやってみたいけど、急ぎます？？あと難易度どれくらいなんだろ

こういうのかな
http://morizyun.github.io/blog/custom-error-404-500-page/

**Comment by yucao24hours** [comment]
そうですね、エラーページをレンダリングする仕組みとそのページを作ることで実現できそうだなと思います。
必要そうなのは、403, 404, 422, 500 かな？

**Comment by shokola** [comment]
https://ja.wikipedia.org/wiki/HTTP%E3%82%B9%E3%83%86%E3%83%BC%E3%82%BF%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%89

その4つで良いと思います :ok_woman: 

402 使ってみたいけど、未実装だし。。

**Comment by 5t111111** [comment]
これ、結構難易度高めのタスクかなと思います。理由はこのあとまとめます。

**Comment by 5t111111** [comment]
難易度が高いと思う理由は、

- production 環境の話であること
- カスタムエラーページについて「これ!」っていう方法がない

## production 環境の話であること

開発時の development 環境であれば、エラーページはデバッグしやすいものであることが重要なので、ここれで言われているのは production 環境の話だと思います。

したがって production 環境で動かしつつこのエラーページを実装していく必要がありますが、production 環境は development 環境と結構違って特殊な動きをするので、ローカルで動かすには色々知っておかないといけないことがあります。例えば、

- CSSなどのアセットは事前にコンパイルしておく必要がある
- コンパイルされたアセットやエラーページなどの静的ファイルはデフォルトでは Rails が扱ってくれない
- SECRET_KEY_BASE などの環境変数の設定が必要

などです。

そんなに手順や押さえどころさえわかれば大丈夫と思いますが、もし初めてであれば結構ハマってしまうかもしれません。

## カスタムエラーページについて「これ!」っていう方法がない

カスタムエラーページをどうやって実現するか、というのにベストプラクティスと呼べる方法がないのが実情だと思っています。主な方法に以下のようなものがありますが、どれも一長一短です。

1. 静的ページとしてエラーページを用意する  
  - 元々用意されているテンプレートを差し変える (足りないものは追加する)
  - [Gakubuchi を使ってみる](http://web-salad.hateblo.jp/entry/2015/08/17/090000)
2. エラーページを動的に生成する  
  - ルーティングでマッチしなかったのを拾ってエラーページを動的に生成する。上でリンクのあった[これ](http://morizyun.github.io/blog/custom-error-404-500-page/)
  - `config.exceptions_app` を指定してエラーページを動的に生成する。[ここ](http://qiita.com/mr-myself/items/c2f4fb2e5dcee6a336f3#comment-23298b703d75b7d27487)に書いてある方法
  - [rambulance を使ってみる](https://github.com/yuki24/rambulance)

ちなみに、Rails 5 ではすべて未検証です…

### 静的ページとしてエラーページを用意する

**元々用意されているテンプレートを差し変える (足りないものは追加する)**

一番シンプルで致命的なデメリットもない方法ですが、単純な静的 HTML であるため、

- Rails のレイアウトや partial が使えない
- テンプレートエンジンが使えない
- `app/assets` にあるスタイルシートも使えない

などの欠点があります。つまりヘッダとかを一般ページと共有できない。ただそれを許容できれば一番良い方法だとは思います。

**Gakubuchi を使ってみる**

この gem はアセットパイプラインを使って静的ページを生成するものです。つまり、最終的な出力は静的ファイルでありながら、テンプレートエンジンの利用や `app/assets` のスタイルシートが使えます。ただ、`render` を使うことはできないので、

- Rails のレイアウトや partial が使えない

という欠点はあります。共通のヘッダやフッタの再利用はできません。逆にそこだけ許容できればいい選択肢だと思います。

### エラーページを動的に生成する

**ルーティングでマッチしなかったのを拾ってエラーページを動的に生成する。**

まず、動的にエラーページを生成する方法には、「Rails 自体が落ちているときにエラーページを表示できない」という問題があります。静的ページであればフロントの Web サーバーがホストしてくれるので、Rails が落ちていても表示できます。これはメンテのときとか障害のときに困ってしまいます(もちろん Kajaeru でそこまで気にすることはないと思いますけど) 。

一方、動的に生成する方法だと、

- Rails のレイアウトや partial が使える
- テンプレートエンジンが使える
- `app/assets` にあるスタイルシートも使える

といった静的ファイルの欠点は解消します。

しれでは、このやり方について。よく見る方法ですが、[ここ](http://qiita.com/mr-myself/items/c2f4fb2e5dcee6a336f3#comment-23298b703d75b7d27487) のコメントにあるようにデメリットが多いので避けた方が無難だと思います。動的にやるならこれ以降の方法にする方がよいでしょう。

**`config.exceptions_app` を指定してエラーページを動的に生成する。**

詳しくは [ここ](http://qiita.com/mr-myself/items/c2f4fb2e5dcee6a336f3#comment-23298b703d75b7d27487) のコメント参照。動的にエラーページを生成する際の方法としては最も Rails way であると思いますが、同じようなことをもっとうまくもっと簡単に実現できる、次の rambulance を使った方がいいと思う…

**rambulance を使ってみる**

動的に生成するならこれを使うのが一番早いでしょう。ただ自分では使ったことがないので何ともコメントできないです。README を読む限りすごく便利そうではあります。

----

ということで、まあ急ぎの issue ではなさそうなのでじっくりやって OK だと思いますが、ちょっと悩むところ多そうだったので事前に共有しておきます。

**Comment by yucao24hours** [comment]
とても詳しくありがとうございますm(_ _)m
わたしがこの issue を立てた時は、ちょうど最近業務で Gakubuchi を使ってみてよさそうだったので、こちらでもそうしたらいいかなーという程度のことを考えていました（その業務でのアプリは Rails 4.2.5 ですが）。

**Comment by shokola** [comment]
おぉGakubuchi経験あるのですね！

**Comment by 5t111111** [comment]
Gakubuchi はホントによいですよ。しかし自分のプロジェクトではアセットパイプラインを使わないので使えないのが切ない…

**Comment by shokola** [comment]
> Rails のレイアウトや partial が使えない

エラーメッセージページには変数渡したりせずに、メッセージだけにして、
個別のデザインにしたらOKってことかな

**Comment by 5t111111** [comment]
> エラーメッセージページには変数渡したりせずに、メッセージだけにして、
> 個別のデザインにしたらOKってことかな

デザインが指すところがどこかにもよりますが Gakubuchi ならスタイルは共有できます。
共有できるスタイルというのは具体的には CSS (SCSS) の共有で、例えば今の Kajaeru は Bootstrap を使っていますが、エラーページのテンプレートの `<head>`  で以下のようにスタイルシートをリンクすれば、それも含めてメインのサイトの CSS を読み込むことができます。

```
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true
```

できないのは、書いたとおり `render` が使えないってことですね。
つまり、

```
= render 'layouts/header'

エラーページ内容本体
  
= render 'layouts/footer'
```

みたいな感じで、ページ共通のヘッダやフッタを使うデザインができないということです。

変数はどうだろ？ものによっては渡せるものもあるかもしれません (グローバルに定義された変数とか) が、あえて渡す必要性がある場面が少ないかもしれません。

**Comment by yucao24hours** [comment]
> わたしがこの issue を立てた時は、ちょうど最近業務で Gakubuchi を使ってみてよさそうだったので、こちらでもそうしたらいいかなーという程度のことを考えていました

と言ってしまいましたが、それに関係なく、やってみたい方法などがありましたらぜひそちらを採用してください :pray:

**Comment by shokola** [comment]
どんな時にどのエラーページ出すかの他に、403, 404, 422, 500ページ、それぞれに出すメッセージ、その後どう誘導するか決めないといけないのだった。。

とりあえず先にという話であれば、適当なメッセージで作ってPR投げて指摘してもらうのが良いですかね？

とリあえずどのページにもTOPページへのリンクは必要かな。

**Comment by shokola** [comment]
422が難しい。。
他社さん参考にしようかな

http://qiita.com/icb54615/items/d6a1b504c4d1a5288d73

**Comment by yucao24hours** [comment]
> どんな時にどのエラーページ出すか

についてですが、この PR では各エラーページを用意して、それらをよりよいしくみで運用するための土台づくりをする（漠然としちゃってますが要するに gem を使って便利に効率よく使いたいという意図です）、がゴールだと思っていたので、たとえば今あるロジックにエラーをさばくためのメソッドを仕込む、とかはしなくていい想定でした！（それはわかってるよってことだったらすみません 🙇 ）
ただわたしもそんなにすごくたくさんの経験があるわけではないので他の方々からもご助言いただきたいところです 🙇

**Comment by yucao24hours** [comment]
> とリあえずどのページにもTOPページへのリンクは必要かな。

それがいいと思います ☺️

**Comment by shokola** [comment]
めちょ🐶に怒られてる・・・
とりあえずエラーページに表示するメッセージを見ていただけたらと思います。

https://github.com/yochiyochirb/kajaeru/pull/160/commits/99e3a078780061a6ff4fca62042996b7b032f5d3

> この issue は「各エラーページを用意して、それらをよりよいしくみで運用するための土台づくりをする（漠然としちゃってますが要するに gem を使って便利に効率よく使いたいという意図です）」がゴール

それから、私もそのゴールで良いと思いますので、
このIssueで用意するものは今回のPushで(中身はともかく)材料は揃った感じでしょうか？

**Comment by yucao24hours** [comment]
ブランチ操作に関する conversation は PR #160 につけますね〜:running:
