### ISSUE TITLE
Wiki を修正する

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kajaeru#104]
- [x] ~~https://github.com/yochiyochirb/kajaeru/wiki/how-to-develop-kajaeru
GitHub Issue を使った運用のときのままになっている。
Trello を使った現在の開発手法にあわせて書き直す。~~ GH issue、というか Waffle に移行したので必要なさそう
- [x] db/seed.rb を使うようにしたことを手順に書いていないので追記する。
- [x] 開発時に rails r のバッチを実行する必要はないので該当行を削除する。

**Comment by yucao24hours** [comment]
まったく別物なタイトルをつけていた...

**Comment by yucao24hours** [comment]
https://github.com/yochiyochirb/kajaeru/wiki/environment/_compare/a9b6bcc%5E...a9b6bcc

これでどうじゃろうか。

**Comment by ManabuSeki** [comment]
@yucao24hours 
開発時にrunnerって必要ですか？
今のところ開発時には必要なさそうなので記述を削除してもいいですか？

**Comment by yucao24hours** [comment]
rails r が必要なのは "開発時" ではなくて "使用の準備をする時" なので、ここには書かなくてよかったですね。
wiki を修正しておきました。ありがとうございます :bow:

**Comment by yucao24hours** [comment]
これ 、done にしてもよかと？

**Comment by ManabuSeki** [comment]
@yucao24hours :ok_hand:

**Comment by yucao24hours** [comment]
いちおう関係するのでメモ
https://github.com/yochiyochirb/kajaeru/blob/master/app/controllers/sessions_controller.rb#L9-L19
