### ISSUE TITLE
テストフレームワークはなににする？

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kajaeru#107]
- RSpec
- minitest
- test-unit
- Cucumber

etc...

はやめにテスト書き始めたいな〜と思っているので、みなさん遠慮無くご意見くださいませ〜。

**Comment by 5t111111** [comment]
minitest :+1:

**Comment by yucao24hours** [comment]
Cucumber🍉

**Comment by yucao24hours** [comment]
このままだとみんなが使い慣れていそうな RSpec がまっさきに却下されるけど...どうしよう（と言いつつ積極的に使おうとはしないわたし。なぜなら DSL を覚えるのが大変だから...）。

別のとこで聞いたほうがいいのかな。

**Comment by yucao24hours** [comment]
ユーザとのインタフェースがあるところはできるだけ Cucumber で書きつつ、必要に応じて単体テストもやったらいいんじゃないかなと思っている。
ひとまず閉じますので、また何かありましたらご意見ください。
