### ISSUE TITLE
CI サービスを変えたい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kajaeru#122]
今は Travis を使っているけど、（Travis だからなのかわからないけど）pass するまでがけっこう遅い気がする。
他のサービスに切り替えることを検討したい。

候補としては

- Wercker http://wercker.com/
- CircleCI https://circleci.com/

あたり。

**Comment by yucao24hours** [comment]
`werkcer` ブランチで werkcer.yml を作って試してみています。
時間帯にもよるのだとは思いますが、同じコミットを push してから build が完了するまで、Travis と Werker では約 9 分の差があり、いずれの push でも Werker のほうが早く完了していました。

TravisCI と CircleCI については、今まで使ったことがあったから、という程度の理由で候補に入れたり採用したりしていましたが、https://idobata.io/ja/archives/organization/yochiyochirb/room/kaja/2016-03-08#message_14758336 でも言及していただいているとおり、このプロジェクトだけにとどまらずわたしたち自身のための経験として今後活かせるのではと思うので、Wercker を使ってみたいなーという気持ちになっています。

**Comment by 5t111111** [comment]
Wercker LGTM

**Comment by yucao24hours** [comment]
あー、ひとつ CircleCI にあって Wercker にない（と思われる）やつ見つけた。
一度テストが落ちて failed になった build がその後の commit push で fixed になったとき、CircleCI は "fixed!" っていうメールが来るけど、Wercker は特になにもない（pass したときの設定に従う）んですね。

**Comment by yucao24hours** [comment]
:memo: Wercker は "ワーカー" とよむ。
