### ISSUE TITLE
.bundle/config に without production 設定を書いて Git 管理してもいいのでは

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kajaeru#130]
というご提案を @ManabuSeki さんからいただきました。
pg gem（PostgreSQL）などは特にインストールでつまづくことが多いけど、ローカルで開発するぶんには不要である（ローカルでは RDBMS は sqlite3 を使用していて、pg はあくまでも Heroku 用である）ので、設定ファイルによってインストールしないように指定することで無駄にトラブルを起こさずに済むのでは、という意図。

**Comment by ManabuSeki** [comment]
これ.bundle配下はgitignoreファイルで除外されているので
```
bundle install --without production
```

これでいいのではないでしょうか

**Comment by yucao24hours** [comment]
あーごめんなさい！ wiki をそう書けばいいんじゃないっていうお話で終わったんでしたっけね :bow:

**Comment by ManabuSeki** [comment]
yes
一回実行したら.bundle/confgにも書き込みされてました

**Comment by yucao24hours** [comment]
これでどうじゃろうか。https://github.com/yochiyochirb/kajaeru/wiki/environment/_compare/2cbe192%5E...2cbe192

**Comment by ManabuSeki** [comment]
:+1:  いいね! LGTM

**Comment by yucao24hours** [comment]
:pray:
