### ISSUE TITLE
bundle update を自動化したい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kajaeru#135]
ふだんの chore や feature の実装でつい忘れがちだけど定期的に確認したいので、自動でやってほしい。

**Comment by 5t111111** [comment]
少し調べて試してみたけど wercker でもいける方法ありますね。

Wercker は WebAPI でビルドのトリガーを引けて、そのときに JSON で環境変数を渡せるので、それで条件分岐すればいけそうです。あとは Heroku Schedular で curl 叩けるのでそこからビルドを実行させれば OK、ていうかもうほとんど試してる間に完成したのでいずれその内容で PR します。

**Comment by shokola** [comment]
:+1: ✨

**Comment by 5t111111** [comment]
circleci-bundle-update-pr にインスパイアされた Gem を作ったので、やろうと思えばすぐできる、と思います。たぶん。。
https://github.com/5t111111/wercker-bundle-update-pr

**Comment by 5t111111** [comment]
README の記載思いっきり間違えてるところがあったので修正しました。念のため。
https://github.com/5t111111/wercker-bundle-update-pr/commit/55fa489000634740ed2be729eacbc31fef7e151f
