### ISSUE TITLE
bundle update の PR のマージをどうするか決めときたい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kajaeru#171]
https://github.com/yochiyochirb/kajaeru/pull/169#issuecomment-207716811

>普通の PR と同じように LGTM を待ってマージする運用だと、(gem の更新頻度にもよるけど) 例えば毎日 PR が出て、前日のが残ったままでマージされていない前日分を消したりとかが大変そうだし、やたら bundle-update-* の PR が溜まって :weary: な感じになりそうなので、どう運用するかは決めておきたいです。

**Comment by 5t111111** [comment]
もう気付いたらその場でマージする感じで回ってるので閉じちゃいますね。
