### ISSUE TITLE
bundle update 実行を毎週に変えたいなら変える方法を検討したい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kajaeru#172]
https://github.com/yochiyochirb/kajaeru/pull/169#issuecomment-207716811

>これも API 呼び出し側の話なので、この PR の内容自体に直接関係することではないですが、bundle update の頻度が高いこと自体はいいことだと思うけど、上記のように運用コスト考えると結構うざいかも、とは思います。

>Heroku Scheduler でがんばる (API リクエストをアプリのタスクでラップして Time.now.wday をチェックして実行を制御するとか) のも1つの案ですが、自分がやるなら AWS Lambda をスケジューリングして使うと思います。たぶん無料枠の範囲で収まるんじゃないかと思いますし。

**Comment by yucao24hours** [comment]
> AWS Lambda をスケジューリングして使うと思います。

これのやりかたをおそわりたい

**Comment by 5t111111** [comment]
ざっくり手順をキャプチャしました。

<img width="849" alt="1" src="https://cloud.githubusercontent.com/assets/333180/15446194/b60d1762-1f52-11e6-94ea-f54cc989968f.png">

----

<img width="894" alt="2" src="https://cloud.githubusercontent.com/assets/333180/15446195/b7a102d2-1f52-11e6-9e42-cf5b0a680821.png">

----

<img width="946" alt="3" src="https://cloud.githubusercontent.com/assets/333180/15446196/bafb25ac-1f52-11e6-9f98-3522aec93ade.png">

----

<img width="1043" alt="4" src="https://cloud.githubusercontent.com/assets/333180/15446197/bdcad282-1f52-11e6-92c9-c2203d6ee5d9.png">

```js
'use strict';
let exec = require('child_process').exec;

let command = "curl -H 'Content-Type: application/json' -H 'Authorization: Bearer xxxxxxxxxxxxxxxxxxx' -X POST -d '{\"applicationId\": \"xxxxxxxxxxxxxx\", \"branch\":\"master\", \"message\":\"Trigger build Kajaeru with BUNDLE_UPDATE\", \"envVars\":[{\"key\":\"BUNDLE_UPDATE\",\"value\":\"true\"}]}' https://app.wercker.com/api/v3/builds";

exports.handler = (event, context, callback) => {

    const child = exec(command, (error) => {
        // Resolve with result of process
        callback(error, 'Process complete!');
    });

    // Log process stdout and stderr
    child.stdout.on('data', console.log);
    child.stderr.on('data', console.error);
};
```

----

<img width="1027" alt="5" src="https://cloud.githubusercontent.com/assets/333180/15446198/c1e23b4e-1f52-11e6-9aef-897e40495795.png">

----

<img width="1275" alt="6" src="https://cloud.githubusercontent.com/assets/333180/15446199/c5c41926-1f52-11e6-8b64-cccf7bee4fda.png">

----

<img width="982" alt="7" src="https://cloud.githubusercontent.com/assets/333180/15446200/c8c9cb02-1f52-11e6-95fe-be5c58c52742.png">

----

<img width="1263" alt="8" src="https://cloud.githubusercontent.com/assets/333180/15446201/cb34d49a-1f52-11e6-88ff-d557b2043173.png">

----

<img width="1132" alt="9" src="https://cloud.githubusercontent.com/assets/333180/15446202/cdc1d03c-1f52-11e6-957a-b5ba11204775.png">

**Comment by yucao24hours** [comment]
うおーありがとうございます😂
あした(今日？)やってみます！

**Comment by yucao24hours** [comment]
設定しました。画面の説明どおりにやったので土曜日の 14:00 に来るのかな。来なかったら reopen します。

**Comment by yucao24hours** [comment]
あ、だめだ。Heroku の既存のやつを止めなきゃ。

**Comment by yucao24hours** [comment]
Heroku Scheduler の job を remove しました。Heroku アプリ自体はいちおう残しておこうかなと思います。
