### ISSUE TITLE
新規投票ができない

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kajaeru#176]
https://github.com/yochiyochirb/kajaeru/blob/master/app/controllers/votes_controller.rb#L36

```ruby
  def require_to_be_voter
    redirect_to root_path, alert: '投票する権限がありません' unless current_user.voter
  end
```

とあるが、`current_user` が未投票の状態では `voter` オブジェクトはないので、このチェックを抜けられずに投票ができない。

**Comment by 5t111111** [comment]
idobata でもコメントしましたが 

> `current_user` が未投票の状態では `voter` オブジェクトはないので、

というのは違ってて、`voter` オブジェクトは seed で作られるものなのでこのケースは発生しないはずです。もし問題があればプロダクトコード側ではなく seed がおかしいか、そもそも seed に頼る仕様に問題がある (`member` に `voter` / `candidate` をどう割り当てるかがアプリケーション的に決まっていない？) ということだと思います。

**Comment by yucao24hours** [comment]
すみません。わたしが手順ミスをしていたせいだったようです。
