### ISSUE TITLE
マイグレーションに失敗する

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kajaeru#178]
https://github.com/yochiyochirb/kajaeru/blob/master/db/migrate/20150307085644_set_constraint_to_vote.rb#L3-L4

で `voter_id` と `candidate_id` に非 NULL 制約をつけるところで、`PG::NotNullViolation: ERROR:  column "voter_id" contains null values` が起きる。

**Comment by yucao24hours** [comment]
これは、もとある Vote オブジェクトが誰によって誰宛に投票されたかを取得して、手作業でつめかえていかないといけないのかな。。
マイグレーションの中にデータ変換コード書きたくない。。

**Comment by 5t111111** [comment]
非 NULL 制約と合致しない仕変前の既存のデータがあるってことですよね？

**Comment by yucao24hours** [comment]
そうですね。今はイベントごとに使いまわせないので、前回の Kaja 選出のときの Vote オブジェクトが残っているためかな、と思っていました。

**Comment by 5t111111** [comment]
イベントごとに使いまわせないのであれば、同一アプリとしてデプロイする意味自体があんまりないですよね。

それなら

1. データを全部消しちゃう
2. 別の Heroku アプリでデプロイする
3. とりあえず現時点では過去データを残したいなら (マイグレーション内にではなく) 独立したバッチとしてデータ変換処理を書いて流す
4. 過去データを残したいとしても #150 の対応後に改めてデータ変換処理を書く

のどれかかな

**Comment by yucao24hours** [comment]
そうですね :disappointed: そのため、 #98 の issue ができたのでした。なので 3 か 4 の対応になるのかなと思ってます。
ただ、1 でも別にかまわないかなという気持ちもあったりして、決めかねています :dash:

**Comment by yucao24hours** [comment]
データ変換スクリプト的なの書こうかなと思ったけど、https://github.com/yochiyochirb/kajaeru/blob/master/db/migrate/20150307084159_add_voter_and_candidates_column.rb でもとの投票データが入っているカラムを消してしまっているので、もうそのデータが残っていないのでは説が浮上してきた。

**Comment by yucao24hours** [comment]
これどうしようもない気がしてるので、もうデータ全夏至でいいんじゃないかしら派
:new_moon_with_face:

**Comment by yucao24hours** [comment]
それでオッケーなら `heroku pg:reset DATABASE` しちゃう

**Comment by 5t111111** [comment]
> もとの投票データが入っているカラムを消してしまっているので、もうそのデータが残っていないのでは説

大事に残す理由がなくなってしまったので全夏至で…

**Comment by yucao24hours** [comment]
いちおうコメントのログだけとったけど、誰に向けたコメントでしょうかクイズみたいになってる :dash:

```ruby
 Vote.all.map{|vote| puts vote.comment if vote.comment.present? }
  Vote Load (3.1ms)  SELECT "votes".* FROM "votes"
いつもありがとう
いつもありがとう
やっぱゆかおさんでしょ！
- ブログがんばっている
こんなに初心者にとっても居心地のいい勉強会を主催してくださっているということは、Rubyの間口を広げてくださっているということに他ならないと思います！いつもありがとうございます！！
よちよち.rbで多くの初心者Rubyistが成長出来ている、その源。
サポート力が高い！
初学者の目線を常に意識してくれていて、よちよちrbの運営を全て一人で担ってくれています。コミュニティの目標を体現している素敵なリーダーです。
みんなが待っていたスタイルの発案者であることと、それを継続しているから。
よちよち.rbの首領。ゆかおさんの行動力、本当に尊敬しています。
ゆかお先生、素晴らしい会をいつもありがとうございます
もちろんゆかおさんです！よちよちに出会えてよかった。こんな素敵なコミュニティを作り、運営していただいている事に感謝してます！！
ゆかおマジ天使
ゆかおさんだからこそ、よちよちというコミュニティが誕生し、ここまで続けられて来られたのだと思います。冠者という言葉がぴったりだと思います！
よちよち.rb創始者であり、これまで週一というペースでミートアップを続けるなどして、よちよちrbを引っ張っていただいているすばらしい功労者だと思います！！
よちよちの皆さん、Kajaeruリリースおめでとうございます！

私はよちよちに参加したことは数回のみで、あとはツイートやFBを見るのみの印象ですが、良く見た時におだいさんがいる安心感のようなものを感じていました。
おだいさんのLTやブログは大変素晴らしく、よちよちの技術の底上げに繋がったと思います。

勿論票が沢山入るであろう、主催者のゆかおさんとサポートがすごかったかとりえさんのW加藤さんもKajaに選んで褒め称えたいです＾＾
閉塞感などで勉強会になかなか継続的に参加できなかった僕ですが、初めて継続的に参加できRubyに対する興味も強くしてくれました。kajaに相応しい方だと思います。
よちよち.rbという勉強会を立ち上げ、rubyコミュニティにruby初級者が入って行きやすいようにしたのが素晴らしいです。
aaaa
```

**Comment by yucao24hours** [comment]
Heroku で backup をとった

**Comment by yucao24hours** [comment]
`heroku pg:reset DATABASE` して、最新までマイグレーションが成功したのを確認したので close
