### ISSUE TITLE
集計画面でアプリが落ちる

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kajaeru#182]
votes/total にアクセスするとアプリが落ちる（漠然）
まだちゃんと原因追求してないです。あとでやる。

**Comment by 5t111111** [comment]
`vote` には `voter` の id が登録されているのに、その id で `member`を探そうとしているから正しい投票者を見つけられず `nil` を叩いてしまっているようです。

#142 対応時の考慮漏れですが (チェック漏れです。ごめんなさい) 、#150 で `Vote#total` には結構手を入れているので、そちらを取り込めば解決しそうですし急いで対応しなくて良いと思います！

**Comment by yucao24hours** [comment]
なるほどー ありがとうございます 🙇 🙇 
では #150 に委ねちゃいますね。#150 からもこちらの issue も connect しておいていただけるとたすかります（作業ふやしちゃってすみません）！

**Comment by 5t111111** [comment]
#150 の取り込みによってこの問題も fix したので閉じます。
