### ISSUE TITLE
Rails のバージョンを上げたい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kajaeru#96]
```shell
$ rails -v
Rails 4.0.3
```

チョット古い

**Comment by 5t111111** [comment]
昨日話した、試しに Rails 5.0.0.beta3 にしてみたやつです。
https://github.com/yochiyochirb/kajaeru/tree/upgrade-to-rails5-feasibility

#108 以外は普通に動いてるっぽいので参考にどうぞ。これをPR出してもいいんですけど、いろいろコンフリクトしてそうでちょっと様子伺ってました。

**Comment by yucao24hours** [comment]
ありがとうございます :bow: つかわせていただきます！

**Comment by yucao24hours** [comment]
っと、いちおう確認しておいたほうがいいかなと思ったのですが、今の時点で 4.2.5.2 ではなくて beta の 5.0.0 にしたいと思った理由って、なんでしょう？
ちょっと、自分のスキル不足もあって今から likely changed なバージョンにすることに不安を覚えているので、そこを解消してからすすめたほうがいいなと思いました。お手数をおかけして、すみません。

**Comment by yucao24hours** [comment]
（フレームワークやライブラリを積極的に新しいバージョンへアップグレードする方針自体には賛成なきもちです :pray: ）

**Comment by 5t111111** [comment]
> っと、いちおう確認しておいたほうがいいかなと思ったのですが、今の時点で 4.2.5.2 ではなくて beta の 5.0.0 にしたいと思った理由って、なんでしょう？

どこに重点を置くか、なんですが、「安定版を使ってスムーズに想定している活動を進めること」以上に、「積極的に安定版じゃないものを使って、時には想定外のトラブルにハマってそれを解決しながら進めること」そして、「もしかしたら、例えば Rails 本体や Gem へのコントリビュートにつながるかも」など、余計な苦労をあえてする選択をしてまで、コミュニティやエコシステムに貢献できる可能性があることをしていきたいというのが、自分が「個人的に」仕事じゃなくてコミュニティ活動に対して求めたいと思うもので、かつ「よちよち(の心をずっとわすれない).rb」に生まれ変わった活動に求めたいと思うものだ、という、何度も言うけど「個人的な」気持ちがあるからです。

あとは `5.0.0.beta3` だと別にそんなに使ってて問題ないから (実際仕事でも新規アプリで使ってて `beta1` とかのときはやばかったけど今はほとんど Gem の issue をあげることもない) 、 likely changed  でも、後から `rc` とか正式リリースのときにちょろっと update するのはコストかかんないだろう、という考えがあります。

@yucao24hours さんがどうしたいかで選択してください！4.2.x にしたいということであればそのアップデートもやってみますよ〜

**Comment by 5t111111** [comment]
あ、もう1つ、単純に今のタイミングでせっかくアップデートするのに、近い将来古いバージョンになるものを使うことの方が余計な負債になる可能性がある、という考えも大きいです。

**Comment by yucao24hours** [comment]
わかりやすいご説明をありがとうございます。
それでは、`5.0.0.beta3` でいくことにしようとおもいます。

**Comment by yucao24hours** [comment]
あ、ちなみに、`upgrade-to-rails5-feasibility` ブランチの変更って、 `rake rails:update` をしたという認識であっていますか？

**Comment by 5t111111** [comment]
> あ、ちなみに、upgrade-to-rails5-feasibility ブランチの変更って、 rake rails:update をした結果という認識であっていますか？

実際には `rake rails:update` をしたそのものの結果ではありません。なぜかというと、`rake rails:update` したときに生成されたり更新されたりするファイルと `rails _5.0.0.beta3_ new ` したときに生成されるものでいくつか差分があって、ちょっと見てみる限りは、おそらくは  `rails _5.0.0.beta3_ new `の側に合わせるのがあるべき姿と判断し (あとはどうせ `secret_token.rb` とか削除しなくちゃいけないファイルもあったので) 、

1. 現在の状態 (Rails 4.0.3) の kajaeru
2. `rake rails:update` した Rails 5.0.0.beta3 の kajaeru
3. `rails _5.0.0.beta3_ new` でできた Rails 5.0.0.beta3 でできた新規 Rails アプリ

を3方向でディレクトリ差分とりながらチマチマ手動で 1. に反映していきました。上で書いた通り、そのときに 2. と 3. で差分があったところは一応内容を見た上で問題なさそうであれば 3. に合わせています。

**Comment by 5t111111** [comment]
すみません、手動の弊害を今まさに見つけてしまいました… :sob: 

https://github.com/yochiyochirb/kajaeru/blob/upgrade-to-rails5-feasibility/config/environments/production.rb#L68

`heyhey` というやる気のない名前が上記したところの 3. の新規アプリ名で、ミスってコピーしたもようです。なんで `kajaeru` にしなかったのか…

```ruby
# config.active_job.queue_name_prefix = "kajaeru_#{Rails.env}"
```

に直してくれると嬉しいです。

あとは気づいてたけどまだやってなかったところで、Rack サーバーを Rails 5.0 のデフォルトに合わせて Puma にしたので、foreman で動かすときは `Procfile` を修正する必要があります。Heroku 用ですね。

**Comment by 5t111111** [comment]
全部目確認でしかないので、最終的にはテスト書いて検証するしかないとは思います。

**Comment by yucao24hours** [comment]
>heyhey というやる気のない名前が上記したところの 3. の新規アプリ名で、ミスってコピーしたもようです。

あっ、そうそう。それを見つけて、「ぜんぶ別のアプリからコピペして持ってきたのかな？」と思ったので聞いてみましたw

いろいろありがとうございます。直しておきます🙋

**Comment by 5t111111** [comment]
ちゃんと検証してないとこで渡しちゃってごめんなさい :bow:

今もっかい全体的に確認しました。上で書いてるとこに加えて、あと↓のところを直してほしいです。ブランチ渡しちゃったのでこっちでやると余計めんどそう。

### `config/cable.yml` がない

`config/cable.yml` が抜けていたので追加してください。
内容はどこか 5.0.0.beta3 から持ってきてもいいけど、これをコピペが一番早そう。
https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/config/cable.yml

### `config/routes.rb` が古い書き方

これまで `Kajaeru::Application` のようになっていたところが  `Rails.application` と書かれるようになっているのでここも以下のように統一しておきたい。

```ruby
Rails.application.routes.draw do
  resources :members, only: %i(index)
  root 'members#index'
  get 'votes/total'
  resources :votes, except: %i(index destroy)

  get '/auth/:provider/callback' => 'sessions#callback'
  get '/signin'                  => 'sessions#new'
  delete '/signout'              => 'sessions#destroy'
end
```

もう他にはないと思います！
