### ISSUE TITLE
主催者および開発者として、Kajaeru を毎回の Ruby Kaja 選定で使いまわせるようにしたい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/kajaeru#98]
主催者および開発者として、Kajaeru を毎回の Ruby Kaja 選定で使いまわせるようにしたい。
なぜなら、そのたびにアプリを作りなおすのはとても大変だからだ。

**Comment by 5t111111** [comment]
この機能を追加するにあたって、Kajaeru の役割的に「異なる回でも `members` は一定なのか / 一定ではないのか」を知りたい (決めたい？) ところです。

汎用的な投票アプリとしては「一定ではない」のが普通かな、と思うのですが、少なくとも今の Kajaeru はある特定のコミュニティ/グループに所属する人だけが対象で、不特定多数の人の投票を認める仕様にはなっておらず、かつ GitHub のアカウントをベースにするので、同じアカウントの member であればそれは同一エンティティと扱うのが自然と思います。

要は「選定イベント用のテーブル」的なやつと `members` が n:n なのか 1:n で済むのかを考えたり、いや、そうじゃなくて「選定イベント用のテーブル」的なやつと直接関連するのは `voters` / `candidates` の方が良いかも、みたいなことを考えたりする材料は欲しい感じです。

**Comment by yucao24hours** [comment]
まったく考えついていませんでしたが、そもそも、「使用者（`members`）は GitHub のコントリビューターとして登録されている人とする」かどうかも、使うコミュニティによって違うかもしれませんねぇ。`members` をどう取り込むかを指定できたほうがいいのかな。csv ファイルとか。。。

**Comment by 5t111111** [comment]
なるほどー。

> そもそも、「使用者（members）は GitHub のコントリビューターとして登録されている人とする」かどうかも、使うコミュニティによって違うかもしれませんねぇ。members をどう取り込むかを指定できたほうがいいのかな。csv ファイルとか。。。

ここから考えるってなるとちょっと重たすぎる感じしますね。となると一旦はこの辺は今やろうとしてることのスコープから外して考えていいんではないでしょうか。

ただ、こういうことを考えると `members` と独立した `roles` が活きてくる感じがしますね。イベントが直接関連するのは `roles` にしといて、で、`roles` は `voter` と `candidate` それぞれがイベントごとに独立して用意されるようにすれば、将来的な `members` の扱いがどういうものになろうとイベントと `roles` 間で仕組みが成立するような気がします。
